all:
	./main.sh ../examples/century_fox.mp4 century_fox_ascii.mp4

.PHONY: clean

clean:
	-rm -rf tmp_ascii
	-rm -rf tmp_thumbnails
	-rm -rf tmp_pict
	-rm -f century_fox_ascii.mp4
	-rm -f audio_track.mp3
